// Generated by CoffeeScript 1.7.1
(function() {
  var express, path;

  express = require('express');

  path = require('path');

  app.configure(function() {
    app.set('port', process.env.PORT || 3000);
    app.set('views', path.join(__dirname, 'views'));
    app.set('view engine', 'ejs');
    app.use(express.favicon());
    app.use(express.logger('dev'));
    app.use(express.json());
    app.use(express.urlencoded());
    app.use(express.methodOverride());
    app.use(app.router);
    app.use(express["static"](path.join(__dirname, 'public')));
    return app.use(require('connect-assets')());
  });

}).call(this);
