// Generated by CoffeeScript 1.7.1
(function() {
  var mongoose, path;

  mongoose = require('mongoose');

  path = require('path');

  require(path.join(__dirname, 'db'));

  global.Comment = mongoose.model('Commenta', new Schema({
    id: ObjectId,
    ref_id: {
      type: String
    },
    user_name: {
      type: String
    },
    comment_cont: {
      type: String,
      validate: /.+/
    },
    create_at: {
      type: Date,
      "default": Date
    },
    remove_opts: {
      type: Boolean,
      "default": false
    }
  }));

}).call(this);
